name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop, feature/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Instalar protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6

      - name: Adicionar binários Go ao PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Instalar buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.55.1'

      - name: Rodar buf generate
        run: buf generate

      - name: Instalar dependências
        run: go mod tidy

      - name: Verificar build
        run: go build ./...

      - name: Rodar testes
        run: go test ./... -v

      - name: Rodar testes com race detection
        run: go test -race ./... -v

      - name: Verificar formatação
        run: go fmt ./...

      - name: Verificar com go vet
        run: go vet ./...

      - name: Verificar cobertura de testes
        run: go test -coverprofile=coverage.out ./...

      - name: Upload coverage para Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella 