name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop, feature/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Instalar buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.55.1'

      - name: Rodar buf generate
        run: buf generate

      - name: Instalar dependências
        run: go mod tidy

      - name: Rodar testes
        run: go test ./... -v 